###############################################################################
# @file      environment_docker.yml
# @brief     Conda environment specification for MonoGS Docker container
# @author    Seungwon Choi
# @email     csw3575@snu.ac.kr
# @date      2025-11-23
# @copyright Seungwon Choi. All rights reserved.
###############################################################################

name: MonoGS
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - tqdm
  - pip:
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
